### PR TITLE
Raise target SDK to 33

### PR DESCRIPTION
**Pull request by raphaelm**
Todo:

- [x] Test that printing works after app was in background for a while and after reboot
  - [x] A12
  - [x] A13
- [x] Update Bluetooth permissions
- [x] Check if [Notification Permission](https://blog.esper.io/android-13-deep-dive/#notification_permission) is required
- [x] Test system printer on Android 13
- [x] Test network printing on Android 13
- [x] Test USB printing on Android 13
  - [x] Test reconnecting USB device and rebooting Android device keeps permission
- [x] Test bluetooth pairing on Android 13
- [x] Test bluetooth printing on Android 13
- [x] Test bluetooth pairing on Android 10, 11, 12
- [x] Test bluetooth printing on Android 10, 11, 12 (test print)
- [x] Test bluetooth printing on Android 10, 11, 12 (service print)
- [x] Test Evolis SDK on Android 13
- [ ] Test Zebra SDK on Android 13

### CODE REVIEW

**Comment by robbi5** [comment]
For bluetooth, the commit https://github.com/pretix/pretixprint-android/commit/2b9c4dd06842d64e8d779b4afb5b76fbe347b24e is relevant. (I'll go and cherry-pick) We have to ask for permissions on the device selection screen.

Not sure what to do about people with an already connected bluetooth printer, they may have to do the connection step again.

**Comment by robbi5** [comment]
Looks like we need the POST_NOTIFICATIONS permission - for the Android Print Service printer.
Added a simple requirement, direct after choosing it as connection type. Don't allowing the permission simply throws you back at the same setup step, this is discouraged by the android documentation. Maybe we should add another setup step that explains the needed permission and shows a hint to the android settings when not given.

**Review by pc-coholic — APPROVED** [review]
Printing Testpages from A11 works fine with LinkOS and LinkOSCard via Eth/Wifi and BT.

**Comment by raphaelm** [comment]
Ok, I think there's a decent chance of LinkOS BT not working on A13, but we currently have no way to test it and don't have any customers we know of that use it.

**Pull request merged**
