### PR TITLE
Lock identical printers used for two use cases

### PR DESCRIPTION
**Pull request by raphaelm**
This might help with some issues where the same USB printer is used twice at the same time. Not sure though since I can't reproduce the issues. Can you check if this makes anything better eg with the bluetooth issues, @robbi5?

### CODE REVIEW

**Comment by robbi5** [comment]
Hmm, thats weird. I've applied the changes to my current android12/maintenance-branch and tested it with the problematic lenovo tablet.
Sometimes the lock is meaningless (the first print completes, there is enough time between first and second print), sometimes the lock itself is working (seeing the calls overlap, second one is waiting), but the second bluetooth connect call is failing again with `read failed, socket might closed or timeout, read ret: -1`.

**Comment by robbi5** [comment]
The crash happens when getting the bluetooth channel/port while connecting, see https://github.com/aosp-mirror/platform_frameworks_base/blob/android-mainline-12.0.0_r114/core/java/android/bluetooth/BluetoothSocket.java#L415
The read from the inputstream there fails with `-1`, this is coming from the native part at
https://github.com/aosp-mirror/platform_frameworks_base/blob/android-mainline-12.0.0_r114/core/jni/android_net_LocalSocketImpl.cpp#L239.

This sounds like the filedescriptor we get from the bluetoothService `getSocketManager().connectSocket()`-call in https://cs.android.com/android/platform/superproject/+/android-mainline-12.0.0_r114:packages/apps/Bluetooth/src/com/android/bluetooth/btservice/BluetoothSocketManagerBinder.java;l=43
is broken, not yet or no longer usable.

Restarting the tablet - and sometimes the printer too - lets it work for some tries again. So it looks like a vendor issue :(

**Comment by raphaelm** [comment]
hmm, okay, but without a reboot no chance so a retry mechanism would not help?

**Comment by robbi5** [comment]
Nope, doesn't seem so. I've added retrying with https://github.com/michaelbull/kotlin-retry, but even longer wait times, even more tries etc. just go straight into closed sockets or even weirder: just nothing happening (output gets written, printer does nothing)

**Comment by raphaelm** [comment]
@robbi5 Coming back to this, as the lock might also be helpful if you use eg the same printer for tickets and badges, the lock did not make anything *worse* in your setup, did it?

**Comment by robbi5** [comment]
Nope, so merging it would be fine, I guess :)

**Pull request merged**
